### ISSUE TITLE
4) Creating Custom Component Instead of ngx-infinite-scroll

### ISSUE THREAD

**Issue by JawaharCoder** [campusrope/campusropepwa#31]
Create new custom component instead of ngx-infinite-scroll.

Shared Directory : Create shared component
Name it as directory name : campusrope-infinite-scroll
selector: "campusrope-infinite-scroll"

Take Input apiurl : string
Take Input datasource : any[]
Take Input youtube : boolean

**Comment by faiyazbits** [comment]
I dont understand this design.can you please  expand more.why should infinite scroll  care about youtube.also if we are using ngx infinite scroll amd simple passing the inputurl and data source to the from this custom component to ngx-infinite-scroll.then there is no point of creating a custom compoennt.

**Comment by faiyazbits** [comment]
Pojnt is only we should write a custom over already existing component then we need to wrap some data or behaviour on top

**Comment by faiyazbits** [comment]
Please make this clear.just trying to understand.i was expecring to just use ngx-infinte-scroll.

**Comment by JawaharCoder** [comment]
We can create a custom component similar to ngx-infinte-scroll.
"campusrope-infinte-scroll" => we can use it for all pages wherever we need.
For trending page also.
The idea is just we have to pass the datasource or api link.
Component will take care everything.
Whether that is displaying single line text or youtube player or any other things for future implementation. We don't want to worry about that.
We can't customize the ngx-infinite-roll as our need.
But our component we can controll anything...
We can write any custom function.
That is the main idea for this component.

Note: I already have the experience like creating custom components and modules.

**Comment by JawaharCoder** [comment]
If suppose for example.
In Admin trending news after listing 1000's data.
We going to add one more item. 
We can simply & efficiently we can refresh our component.
But ngx that is not possible

**Comment by faiyazbits** [comment]
This is great .@jawahar.go ahead.i though we are gonna use ngrxscroll.now only i understand you are suggesting our own implementation .i had the same idea before

**Comment by faiyazbits** [comment]
But i thought why reinvent the wheel.if you can create your own implo go ahead

**Comment by faiyazbits** [comment]
I even had an article before on how to fo this
https://blog.strongbrew.io/infinite-scroll-with-rxjs-and-angular2/

**Comment by faiyazbits** [comment]
Sorry for the confusion.

**Comment by JawaharCoder** [comment]
Great Faiyaz, I will read this and take some reference if need.
{ That is also some developer like us developed earlier.
But the thing is we not blogging that... }
We can create our own ideas... 
Thanks for sharing this...

**Comment by faiyazbits** [comment]
Just waiting to see and learn from your implementation.just make it reactive as all our services are reactive and they play well.you can make use of the above link.its clean

**Comment by faiyazbits** [comment]
We can create our own ideas but we should not doing it just for the sake of it.

**Comment by faiyazbits** [comment]
Whats best for project or use case should be the intention and driving force.

**Comment by faiyazbits** [comment]
Please go ahead.great work guys by the way

**Comment by faiyazbits** [comment]
I really needed this kind of discussion for a long time

**Comment by JawaharCoder** [comment]
Thanks bro,
Also for me this is a new experience..
Thanks for your ideas and advice...
I will definitely use the link and pass the link when I'm creating the issues ;-)

**Comment by faiyazbits** [comment]
Fantastic
