### ISSUE TITLE
7) CampusRopeIScrollComponent Custom Infinite Scroll Implementation.

### ISSUE THREAD

**Issue by JawaharCoder** [campusrope/campusropepwa#36]
Component name : CampusRopeIScrollComponent
HTML file name : campusrope-infinite-scroll.component.html
Shared Component.

https://github.com/sujitpatil72/YT-INF-SCROLL.git

Please use above GitHub link.
And implement the scroll infinite-scroll
to this component.

Test with at least 5000 records.

Once completed this task 
please update the code in your own repo and share that link to Akshay on Skype.

And comment below the testing feedback the scroll of speed and response.

Maximum estimated time  - 2hrs

Goal - find innovative ways to solve this problem.

**Comment by sujitpatil72** [comment]
Hi, Does someone knows any website where I will get 5000 Youtube video URLs in JSON format.

**Comment by JawaharCoder** [comment]
Please find this attachment.

[YouTube-Playlist.zip](https://github.com/campusrope/campusropepwa/files/3855242/YouTube-Playlist.zip)

This zip contains excel sheet data you can convert this to json.
#youtubevideostojson #youtubeplaylisttojson

**Comment by sujitpatil72** [comment]
Hi, I have attached the JSON file with more than 5000 Youtube URLs data if someone wants to use it.
[youtube.json.zip](https://github.com/campusrope/campusropepwa/files/3855304/youtube.json.zip)
