### ISSUE TITLE
A01. Youtube Player automatic play/pause on scroll.

### ISSUE THREAD

**Issue by akshay72222** [campusrope/campusropepwa#37]
### Objective:
Design a feeds, embedded with 10 youtube videos that play/pause automatically on scroll for desktop browser UI only.  

#

### Technolgies:
Angular 8, Youtube videos - Any 10 video links pass the array data from Angular component and render it on html.

#

### User Story
As a user, when I open feeds, the youtube video in the top should start playing automatically in mute until the next video comes in the top while i am scrolling, so that i can unmute the video if i find it interesting enough.    

#

> ## Please take inspiration form twitter to get better understanding of the user experience.

**Comment by JawaharCoder** [comment]
![image_2019_11_11T07_14_22_715Z](https://user-images.githubusercontent.com/34167383/69172168-58374700-0b23-11ea-9469-437021443adf.png)
Please find the attachment for sample design

**Comment by akshay72222** [comment]
![Youtube](https://user-images.githubusercontent.com/22296552/69341326-60ac9080-0c8f-11ea-9eb2-58a85e25b66b.PNG)

The YouTube player should have the following option given in the image like - video quality settings, fullscreen button etc.

Please find live example from this link
https://www.hahaha.com/en/funny-videos?todays-video

**Comment by akshay72222** [comment]
The default video quality of the videos should be 360p
