### ISSUE TITLE
A02. Create Simple Form Using Angular Manage Data with StrApi 

### ISSUE THREAD

**Issue by JawaharCoder** [campusrope/campusropepwa#39]
### Objective:
Create a simple form using Angular.
Form fields HeadLine, YoutubeURL, State.
Implementing CRUD operation with strapi.
#

### Technolgies:
Front End: Angular 8, 
Back End: https://strapi.io/

#

### User Story
As a user, I want to fill in forms and create data. I also want the access to delete and update that data.

> The data should be stored in strapi cms

#

Maximum Estimated hours - 2

**Comment by faiyazbits** [comment]
strapi already have an admin portal that is capable of doing this. may i please know the purpose of it

**Comment by JawaharCoder** [comment]
Assessment purpose simple task for testing and hiring the new contributors, Just they can able to work with API calls like that. Only for frontend developers.

**Comment by faiyazbits** [comment]
i see. thats a good idea. make sure this code doesnt get bundled in the app code
