### ISSUE TITLE
108.make a click to call component

### ISSUE THREAD

**Issue by faiyazbits** [campusrope/campusropepwa#9]
this should take input a phone number string

**Comment by faiyazbits** [comment]
Create a  component called click-to-call in shared . this should accept a phone number as input . and should render a link like span or div. when clicked opens a modal where we should ask copy number and call number.whecopy number is clicked ,number should get copied to clipboard ,when call is  clicked , href tel deep linking is triggered and call is made.

**Comment by umarfarooq95** [comment]
how to pass an input for click to call component. click to call component is a dialog so, we can pass data through dialog modal not in input. i will give PR. please review it
